import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { pathname: string }; // Access params to check route
}) {
  const pathname = params.pathname; // Using params to get the pathname

  let pageClass = "";
  if (pathname === "/digitalTransformation") pageClass = "digital-transformation-page";
  else if (pathname === "/digitalMarketing") pageClass = "digital-marketing-page";
  else if (pathname === "/enterpriseSolutions") pageClass = "enterprise-solutions-page";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${pageClass}`}
      >
        {children}
      </body>
    </html>
  );
}
